name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Pylint action
      # You may pin to the exact commit or the version.
      # uses: gabriel-milan/action-pylint@5a2e0c4a6af3a7fac3c45e724b96d45f2a7a4352
      uses: gabriel-milan/action-pylint@v1
      with:
        # Path of files
        path: ../../mayan/
